#!/bin/bash

if ! grep -q "/boot/rpi" /etc/fstab; then
  echo "Mount point \`/boot/rpi' does not exist in fstab file."
  echo "You need to update firmware files manually, which is installed to /usr/lib/rpi64/boot."
  echo "Or add the boot partition to fstab and try again."
  exit 0
fi

if ! mount -a; then
  echo "Unable to mount /boot/rpi! Please check your fstab file. Not treating as an error, exiting cleanly."
  exit 0
fi

if [ -e /boot/rpi/kernel8.img ]; then
  echo "Copying new firmware..."
  cp /usr/lib/rpi64/boot/*.{elf,bin,dat} /boot/rpi/
else
  echo "Copying kernel and firmware..."
  cp -r /usr/lib/rpi64/boot/* /boot/rpi/
  cp -r /usr/lib/rpi64/kernel/* /boot/rpi/
fi

if [ ! -e /boot/rpi/config.txt ]; then
  echo "Creating config.txt..."
  cp /usr/lib/rpi64/config/config.txt /boot/rpi/config.txt
fi

if [ ! -e /boot/rpi/distcfg.txt ]; then
  echo "Creating distcfg.txt..."
  cp /usr/lib/rpi64/config/distcfg.txt /boot/rpi/distcfg.txt
fi

if [ ! -e /boot/rpi/cmdline.txt ]; then
  PARTUUID="$(lsblk -x MOUNTPOINT -o MOUNTPOINT,PARTUUID | egrep '^/\s' | awk '{print $2}')"
  echo "Generating new cmdline.txt..."
  echo -n "console=serial0,115200 console=tty1 root=PARTUUID=${PARTUUID} rw elevator=deadline fsck.repair=yes rootwait" > /boot/rpi/cmdline.txt
fi
