#!/bin/sh

if [ "$1" == "/dev/EC25.NMEA" ] && [ "$2" == "ACTIVATE" ]; then
    echo "AT+QGPS=1" | atinout - /dev/EC25.AT -
elif [ "$1" == "/dev/EC25.NMEA" ] && [ "$2" == "DEACTIVATE" ]; then
    echo "AT+QGPSEND" | atinout - /dev/EC25.AT -
else
    echo "Unhandled argument: $1 $2"
    exit 1
fi
