#! /bin/busybox ash
/bin/busybox echo "Entered initramfs" > /dev/tty0
/bin/busybox mount -t devtmpfs devtmpfs /dev
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t proc proc /proc
/bin/busybox echo "Devtmpfs mounted" > /dev/tty0

/bin/busybox mdev -s
/bin/busybox echo "Device populated" > /dev/tty0

/bin/busybox echo "Waiting for mmcblk0p1" > /dev/tty0
while /bin/busybox [ ! -e /dev/mmcblk0p1 ]
do
/bin/busybox sleep 1
/bin/busybox mdev -s
done

/bin/busybox mount /dev/mmcblk0p1 /aosc
/bin/busybox echo "mmcblk0p1 mounted" > /dev/tty0

S=$(/bin/busybox tty)
/bin/busybox echo $S > /dev/tty0

exec /bin/busybox switch_root /aosc /sbin/init >/dev/tty0 2>&1 </dev/tty0
/bin/busybox echo "FAILED!!!" >/dev/tty0
/bin/busybox sleep 1000000
